#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Usage: $0 <DB_USER> <DB_NAME>"
  exit 1
fi

DB_USER="$1"
DB_NAME="$2"

if ! psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1; then
  echo "L'utilisateur $DB_USER n'existe pas."
  exit 1
fi

if ! psql postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
  echo "La base de données $DB_NAME n'existe pas."
  exit 1
fi

read -p "Faut-il vraiment supprimer l'utilisateur $DB_USER et la BdD $DB_NAME ? ('Oui' pour confirmer) " confirmation
if [ "$confirmation" != "Oui" ]; then
  echo "Suppression annulée."
  exit 1
fi

psql postgres << EOF
DROP DATABASE $DB_NAME;
DROP USER $DB_USER;
\q
EOF

exit 0
